# Generated by Django 4.0.3 on 2022-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='hints',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='learningResources',
        ),
    ]
