# Generated by Django 4.0.3 on 2022-04-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_learningresources_problem_resources_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.CharField(default='www.math.com', max_length=255),
        ),
    ]
