# Generated by Django 4.0.3 on 2022-04-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_remove_problem_answer_remove_problem_hints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='content',
        ),
    ]
