# Generated by Django 4.0.3 on 2022-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_problem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='resources',
            field=models.TextField(),
        ),
    ]
