# Generated by Django 4.0.3 on 2022-04-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_content_alter_problem_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='live_status',
            field=models.BooleanField(default=False),
        ),
    ]
