# Generated by Django 4.0.3 on 2022-04-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_live_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='correctAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='hintsUsed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='problem',
            name='incorrectAnswers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='live_status',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='resources',
            field=models.TextField(max_length=255),
        ),
    ]
